# -*- coding: utf-8 -*-

REGEX_ENTITIES_MX = r"(\sSC.*)|(\sS\s?A ?D?E?.*\b)|(\sSAPI\b.*)|(\sS D?E? ?R?L?\b.*)"

MX_BANK_COLUMNS = [
    #RSM
    "Fecha Operación",
    "Concepto",
    "Referencia",
    "Referencia Ampliada",
    "Cargo",
    "Abono",
    "Saldo",
    #BNC
    "Cuenta beneficiaria",
    "Titular cuenta",
    "Número banco receptor",
    "Cuenta ordenante",
    "Cuenta CLABE ordenante",
    "Divisa",
    "Titular cuenta ordenante",
    "RFC ordenante",
    "Fecha de pago",
    "Número de movimiento",
    "Código de leyenda",
    "Concepto",
    "Debe-Haber",
    "Importe",
    "Efectivo real",
    "Referencia númerica",
    "Referencia ampliada",
    "Forma de pago",
    #SPEI
    "Fecha", 
    "Referencia numerica", 
    "Concepto de codigo de leyenda", 
    "Referencia", 
    "Concepto de pago", 
    "Importe", 
    "Saldo", 
    "Banco ordenante", 
    "Nombre ordenante", 
    "Cuenta ordenante", 
    "Banco beneficiario", 
    "Nombre beneficiario", 
    "Cuenta beneficiario", 
    "Clave de rastreo", 
    "Estado del pago", 
    "Motivo de devolucion",
    #CFDI
    "Clave producto", 
    "Fecha de pago", 
    "Forma de pago", 
    "Moneda", 
    "Tipo de cambio", 
    "Monto", 
    "Número de folio de operación", 
    "Movimiento en cuenta", 
    "RFC Banco ordenante", 
    "Nombre banco ordenante", 
    "RFC ordenante", 
    "Nombre ordenante", 
    "Cuenta ordenante", 
    "RFC Banco beneficiario", 
    "Cuenta beneficiaria", 
    "Tipo de cadena de pago", 
    "Certificado del pago", 
    "Cadena original", 
    "Sello de pago", 
    "Folio de operación", 
    "Cuenta"
]
